//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GisVN.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GisVN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ nhà/căn hộ.
        /// </summary>
        public static string DiaChiNha {
            get {
                return ResourceManager.GetString("DiaChiNha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ thửa.
        /// </summary>
        public static string DiaChiThua {
            get {
                return ResourceManager.GetString("DiaChiThua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại giấy.
        /// </summary>
        public static string LoaiGiay {
            get {
                return ResourceManager.GetString("LoaiGiay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm sinh.
        /// </summary>
        public static string NamSinh {
            get {
                return ResourceManager.GetString("NamSinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày vào sổ.
        /// </summary>
        public static string NgayVaoSo {
            get {
                return ResourceManager.GetString("NgayVaoSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều kiện tìm kiếm.
        /// </summary>
        public static string SearchCondition {
            get {
                return ResourceManager.GetString("SearchCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả tìm kiếm.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND/Hộ chiếu.
        /// </summary>
        public static string SoCMND {
            get {
                return ResourceManager.GetString("SoCMND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hiệu.
        /// </summary>
        public static string SoHieu {
            get {
                return ResourceManager.GetString("SoHieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hs gốc cũ.
        /// </summary>
        public static string SoHoSoCu {
            get {
                return ResourceManager.GetString("SoHoSoCu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hồ sơ gốc.
        /// </summary>
        public static string SoHoSoGoc {
            get {
                return ResourceManager.GetString("SoHoSoGoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số nhà/căn hộ.
        /// </summary>
        public static string SoNha {
            get {
                return ResourceManager.GetString("SoNha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số nhà/căn hộ cũ.
        /// </summary>
        public static string SoNhaCu {
            get {
                return ResourceManager.GetString("SoNhaCu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tờ bản đồ.
        /// </summary>
        public static string SoToBanDo {
            get {
                return ResourceManager.GetString("SoToBanDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tờ bản đồ cũ.
        /// </summary>
        public static string SoToBanDoCu {
            get {
                return ResourceManager.GetString("SoToBanDoCu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số vào sổ.
        /// </summary>
        public static string SoVaoSo {
            get {
                return ResourceManager.GetString("SoVaoSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thứ tự thửa.
        /// </summary>
        public static string STTThua {
            get {
                return ResourceManager.GetString("STTThua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thứ tự thửa cũ.
        /// </summary>
        public static string STTTHuaCu {
            get {
                return ResourceManager.GetString("STTTHuaCu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chủ.
        /// </summary>
        public static string TenChu {
            get {
                return ResourceManager.GetString("TenChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin trên giấy chứng nhận.
        /// </summary>
        public static string ThongTinTrenGiay {
            get {
                return ResourceManager.GetString("ThongTinTrenGiay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng giấy.
        /// </summary>
        public static string TinhTrangGiay {
            get {
                return ResourceManager.GetString("TinhTrangGiay", resourceCulture);
            }
        }
    }
}
